syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.grpc.workload";
option java_outer_classname = "TrainerWorkloadProto";

package workload;

service TrainerWorkloadGrpcService {
  rpc UpdateWorkload (WorkloadRequest) returns (WorkloadResponse);
}

enum ActionType {
  ADD = 0;
  DELETE = 1;
}

message WorkloadRequest {
  string trainerUsername = 1;
  string trainerFirstName = 2;
  string trainerLastName = 3;
  bool isActive = 4;
  string trainingDate = 5; // ISO-8601 string: YYYY-MM-DD
  int32 trainingDuration = 6;
  ActionType actionType = 7;
}

message WorkloadResponse {
  bool success = 1;
  string message = 2;
}