spring.application.name=gym_crm

storage.trainer-file-path=trainers.json
storage.trainee-file-path=trainees.json
storage.training-type-file-path=training-types.json
storage.training-file-path=trainings.json

spring.datasource.url=jdbc:postgresql://localhost:5435/gym_crm_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop