spring.application.name=gym_crm

spring.datasource.url=jdbc:postgresql://localhost:5435/gym_crm_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-init.sql
spring.jpa.defer-datasource-initialization=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%thread]){magenta} %clr([tx:%X{transactionId}]){cyan} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n