# Datasource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DDL & Schema Management
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=false

# Logging Configuration
logging.level.root=WARN
logging.level.com.example.gym_crm=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=ERROR
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [tx:%X{transactionId}] %-5level %logger{36} - %msg%n

# Actuator Security
management.endpoint.health.show-details=never