spring.application.name=trainer-workload-service
server.port=8082

# Shared secret with core-service
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Eureka Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging Format
logging.level.root=WARN
logging.level.com.example.trainerworkloadservice=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%thread]){magenta} %clr([tx:%X{transactionId}]){cyan} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n

grpc.server.port=9090